import { readFileSync } from "node:fs";
import { describe, expect, expectTypeOf, it } from "vitest";
import type { CoachEngine as ContractCoachEngine } from "@enduragent/coach-contract";
import type { CoachEngine, CreateCoachEngineInput, EngineHostPorts } from "@enduragent/engine";
import type { Sport } from "@enduragent/engine/sport";

// @ts-expect-error The export map must deny every engine-internal deep import.
import type { EngineHostPorts as ForbiddenDeepImport } from "@enduragent/engine/host-ports";

const deepImportMustStayUnresolvable = null as unknown as ForbiddenDeepImport;
void deepImportMustStayUnresolvable;

describe("engine scaffold", () => {
  it("pins the only two public package entry points", () => {
    const manifest = JSON.parse(
      readFileSync(new URL("../package.json", import.meta.url), "utf8"),
    ) as { exports: unknown };
    expect(manifest.exports).toEqual({
      ".": {
        types: "./dist/index.d.ts",
        import: "./dist/index.js",
      },
      "./sport": {
        types: "./dist/sport.d.ts",
        import: "./dist/sport.js",
      },
    });
  });

  it("exports only the canonical factory and authorized account-id helper at runtime", async () => {
    expect(Object.keys(await import("@enduragent/engine")).sort()).toEqual([
      "API_KEY_BILLING_IDENTITY_LINE",
      "ATHLETE_CONTEXT_FENCE_CLOSE",
      "ATHLETE_CONTEXT_FENCE_OPEN",
      "ATHLETE_CONTEXT_TRUNCATION_NOTICE",
      "CLAUDE_CLI_PRICE_TABLE",
      "CODEX_AGENT_PRICE_TABLE",
      "COMPACTION_SUMMARY_END_MARKER",
      "COMPACTION_SUMMARY_MARKER",
      "ClaudeCliConfigError",
      "ClaudeWorkingAreaError",
      "CodexAgentConfigError",
      "DATE_KEY_RE",
      "EMPTY_PROVENANCE",
      "FENCE_TOKEN_REPLACEMENT",
      "GARMIN_DATA_ATTRIBUTION",
      "INTERVALS_LIST_MAX_RANGE_DAYS",
      "PLAN_AUTO_APPLY_RACE_WINDOW_DAYS",
      "PLAN_MIRROR_DAYS",
      "PLAN_MIRROR_EXTERNAL_ID_PREFIX",
      "PlanProposalError",
      "PlanStartDateError",
      "PlanUndoError",
      "PlanWorkoutDriftError",
      "RaceCourseLifecycleError",
      "SUMMARY_PREFIX",
      "TOOL_RESULT_SHARE",
      "UNKNOWN_PROVENANCE",
      "WEEKLY_REVIEW_RACE_QUIET_DAYS",
      "WORKOUT_MATCH_AS_PLANNED_MAX_SECONDS",
      "WORKOUT_MATCH_AS_PLANNED_MIN_SECONDS",
      "WORKOUT_MATCH_AS_PLANNED_RATIO",
      "WORKOUT_MATCH_DURATION_MAX_SECONDS",
      "WORKOUT_MATCH_DURATION_MIN_SECONDS",
      "WORKOUT_MATCH_DURATION_RATIO",
      "_resetOrphanWarnCacheForTesting",
      "acceptParsedRaceCourse",
      "activatePlanDraft",
      "adoptProviderWorkoutEdit",
      "applyPlanStartDatePreview",
      "applyValidatedPlanProposal",
      "applyValidatedPlanUndo",
      "approvePlanReplacement",
      "beginRaceCourseParsing",
      "beginRaceCourseRemoval",
      "bindToolResult",
      "boundToolResultProvenance",
      "cacheReadSavingsUsd",
      "capToolResult",
      "capturePlanProposalBase",
      "carryBoundToolResultProvenance",
      "classifyActivities",
      "classifyActivity",
      "classifySpendCaching",
      "classifyTrustedSource",
      "claudeCliCacheReadSavingsUsd",
      "claudeIdentityLine",
      "cleanupPlanMirror",
      "codexAgentCacheReadSavingsUsd",
      "codexIdentityLine",
      "completeRaceCourseRecalculation",
      "composeWeeklyReview",
      "contentDigest",
      "createAttachmentCapabilityResolver",
      "createClaudeWorkingArea",
      "createCoachEngine",
      "dateKeySchema",
      "demoteSummaryHeadings",
      "encodePlanProposalBase",
      "encodePlanProposalMutation",
      "ensureClaudeCliReady",
      "ensureCodexAgentReady",
      "evaluatePlanIntakeReadiness",
      "executePlanFtpTransition",
      "extractAccountId",
      "failRaceCourseRecalculation",
      "failedPlanReadiness",
      "formatCompactionNote",
      "getMessageProvenance",
      "invalidateClaudeAccountProbeCache",
      "invalidateCodexAgentProbeCache",
      "isNonEmptyData",
      "isProviderAuthFailure",
      "isRacePlanWorkout",
      "isSourceProvenance",
      "isUntrustedEnvelope",
      "makeSummaryMessage",
      "markProviderAuthFailure",
      "markUntrustedResult",
      "naturalPlanCompletionDue",
      "openRaceCoursePicker",
      "orderPlanAttentionItems",
      "parseOpenRouterModelMetadataSnapshot",
      "parsePlanProposalMutation",
      "persistCompactionSummary",
      "planFinalCivilDateKey",
      "planMirrorExternalId",
      "planMirrorExternalIdPrefix",
      "planWorkoutDriftSnapshot",
      "previewPlanStartDate",
      "priceClaudeCliInclusiveUsage",
      "priceCodexAgentInclusiveUsage",
      "priceInclusiveUsage",
      "probeClaudeAccountCached",
      "projectPlanHistoryEligibility",
      "projectPlanProposalDiff",
      "projectPlanReadiness",
      "projectPlanReconciliation",
      "projectPlanSeason",
      "projectWorkoutMatches",
      "provenanceForSourceBearingData",
      "provenanceOfMessages",
      "providerWorkoutDriftSnapshot",
      "raceOutcomeDue",
      "recheckClaudeAccount",
      "reconcileActivePlanWindow",
      "refreshPlanWorkoutDrifts",
      "refreshPlanWorkoutMatches",
      "refreshingPlanReadiness",
      "rejectRaceCourseFile",
      "renderGarminAttribution",
      "resolveClaudeCliPriceId",
      "resolveCodexAgentPriceId",
      "restorePlanWorkout",
      "retryRaceCourseRecalculation",
      "revalidatePlanProposalPremises",
      "sanitizeUntrustedText",
      "selectWeeklyReviewWindow",
      "setMessageProvenance",
      "splitHistoryByBudget",
      "taperRefusalReadiness",
      "transportForProvider",
      "truncateUtf16Safe",
      "unionProvenance",
      "unwrapBoundToolResult",
      "useRouteWithoutElevation",
      "validateListRange",
      "validatePlanAutoApply",
      "validatePlanProposal",
      "validatePlanUndo",
      "validateWorkoutCreationDate",
      "verifyPlanCleanup",
      "verifyPlanMirror",
      "warnOrphanSections",
      "wrapAthleteContextFence",
    ]);
  });

  it("reuses the contract and pins the injected factory input", () => {
    expectTypeOf<CoachEngine>().toEqualTypeOf<ContractCoachEngine>();
    expectTypeOf<CreateCoachEngineInput>().toEqualTypeOf<{
      readonly sport: Sport;
      readonly ports: EngineHostPorts;
    }>();
  });
});
