name = "enduragent-api-fallback"
main = "model-catalog-api-fallback.worker.ts"
compatibility_date = "2026-09-14"
workers_dev = false

[env.production]
name = "enduragent-api-fallback"
workers_dev = false

[[env.production.routes]]
pattern = "api.enduragent.icu"
custom_domain = true

[env.staging]
name = "enduragent-api-fallback-staging"
workers_dev = false

[[env.staging.routes]]
pattern = "api-staging.enduragent.icu"
custom_domain = true
