name = "enduragent-model-catalog-config"
compatibility_date = "2026-09-14"
workers_dev = false
preview_urls = false

[env.production]
name = "enduragent-model-catalog"
workers_dev = false
preview_urls = false

[env.production.assets]
directory = "./.model-catalog-assets"
run_worker_first = false
html_handling = "none"
not_found_handling = "none"

[[env.production.routes]]
pattern = "api.enduragent.icu"
custom_domain = true

[env.staging]
name = "enduragent-model-catalog-staging"
workers_dev = false
preview_urls = false

[env.staging.assets]
directory = "./.model-catalog-assets"
run_worker_first = false
html_handling = "none"
not_found_handling = "none"

[[env.staging.routes]]
pattern = "api-staging.enduragent.icu"
custom_domain = true
